import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { requireModule } from "../../middleware/tenantContext.js";

export const productsRouter = Router();
productsRouter.use(requireModule("PRODUCTS"));
const schema = z.object({ storeId: z.string().cuid(), name: z.string().trim().min(2).max(120), sku: z.string().trim().min(2).max(40).transform((v) => v.toUpperCase()), unit: z.string().trim().min(1).max(20).default("each"), quantity: z.coerce.number().min(0), reorderLevel: z.coerce.number().min(0), isActive: z.boolean().default(true) });
const updateSchema = schema.omit({ quantity: true }).partial();
const movementSchema = z.object({ type: z.enum(["RECEIPT", "DISPATCH", "ADJUSTMENT"]), quantity: z.coerce.number().finite().refine((value) => value !== 0, "Quantity cannot be zero"), note: z.string().trim().max(500).optional(), occurredAt: z.coerce.date().optional() }).superRefine((value, context) => { if (["RECEIPT", "DISPATCH"].includes(value.type) && value.quantity < 0) context.addIssue({ code: "custom", message: "Receipt and dispatch quantities must be positive", path: ["quantity"] }); });
const tenantId = (req: { tenantId?: string }) => { if (!req.tenantId) throw new Error("Tenant context is required"); return req.tenantId; };

productsRouter.get("/", async (req, res) => res.json({ products: await prisma.inventoryItem.findMany({ where: { tenantId: tenantId(req) }, include: { store: true, menuItems: true, menuIngredients: { include: { menuItem: true } } }, orderBy: { name: "asc" } }) }));
productsRouter.get("/stores", async (req, res) => res.json({ stores: await prisma.store.findMany({ where: { tenantId: tenantId(req), isActive: true }, orderBy: { name: "asc" } }) }));
productsRouter.post("/", async (req, res) => { const data = schema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid product", details: data.error.flatten() }); return; } const tid = tenantId(req); const store = await prisma.store.findFirst({ where: { id: data.data.storeId, tenantId: tid, isActive: true } }); if (!store) { res.status(400).json({ error: "Choose an active store from this property" }); return; } const product = await prisma.$transaction(async (tx) => { const created = await tx.inventoryItem.create({ data: { tenantId: tid, ...data.data } }); if (data.data.quantity > 0) await tx.inventoryMovement.create({ data: { tenantId: tid, inventoryItemId: created.id, storeId: created.storeId, type: "RECEIPT", quantity: data.data.quantity, note: "Opening balance", performedBy: req.userId } }); return created; }); res.status(201).json({ product }); });
productsRouter.patch("/:id", async (req, res) => { const data = updateSchema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid product", details: data.error.flatten() }); return; } const updated = await prisma.inventoryItem.updateMany({ where: { id: req.params.id, tenantId: tenantId(req) }, data: data.data }); if (!updated.count) { res.status(404).json({ error: "Product not found" }); return; } res.json({ product: await prisma.inventoryItem.findUniqueOrThrow({ where: { id: req.params.id } }) }); });
productsRouter.delete("/:id", async (req, res) => { const deleted = await prisma.inventoryItem.deleteMany({ where: { id: req.params.id, tenantId: tenantId(req) } }); if (!deleted.count) { res.status(404).json({ error: "Product not found" }); return; } res.status(204).send(); });
productsRouter.get("/:id/movements", async (req, res) => { const product = await prisma.inventoryItem.findFirst({ where: { id: req.params.id, tenantId: tenantId(req) } }); if (!product) { res.status(404).json({ error: "Product not found" }); return; } res.json({ product, movements: await prisma.inventoryMovement.findMany({ where: { inventoryItemId: product.id, tenantId: product.tenantId }, include: { store: true }, orderBy: { occurredAt: "desc" } }) }); });
productsRouter.post("/:id/movements", async (req, res) => { const data = movementSchema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid inventory movement", details: data.error.flatten() }); return; } const tid = tenantId(req); const product = await prisma.inventoryItem.findFirst({ where: { id: req.params.id, tenantId: tid } }); if (!product) { res.status(404).json({ error: "Product not found" }); return; } const signedQuantity = data.data.type === "DISPATCH" ? -data.data.quantity : data.data.quantity; const result = await prisma.$transaction(async (tx) => { const updated = await tx.inventoryItem.updateMany({ where: { id: product.id, quantity: { gte: signedQuantity < 0 ? Math.abs(signedQuantity) : 0 } }, data: { quantity: { increment: signedQuantity } } }); if (!updated.count) return null; return tx.inventoryMovement.create({ data: { tenantId: tid, inventoryItemId: product.id, storeId: product.storeId, type: data.data.type, quantity: signedQuantity, note: data.data.note, occurredAt: data.data.occurredAt, performedBy: req.userId } }); }); if (!result) { res.status(400).json({ error: "Dispatch would take stock below zero" }); return; } res.status(201).json({ movement: result, product: await prisma.inventoryItem.findUniqueOrThrow({ where: { id: product.id } }) }); });
